kiosksurvey/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^surveys/', include('surveys.urls')),
    url(r'^admin/', admin.site.urls),
]

surveys/urls.py
from django.conf.urls import url

from . import views

app_name = 'surveys'
urlpatterns = [
    # ex: /surveys/
    url(r'^$', views.index, name='index'),
    # ex: /surveys/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.survey_administration, name='detail'),
    # ex: /surveys/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /surveys/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

urls.py
ECHO is on.

surveys/models.py
from django.db import models

# Pretty much straight out of the polls tutorial for now... we may get fancier later


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.option_text

surveys/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Question, Option


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'surveys/index.html', context)


def survey_administration(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'surveys/detail.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_option = question.option_set.get(pk=request.POST['option'])
    except (KeyError, Option.DoesNotExist):
        return render(request, 'surveys/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_option.votes += 1
        selected_option.save()

        return HttpResponseRedirect(reverse('surveys:detail', args=(question.id,)))

surveys/templates/surveys/detail.html
<style type = "text/css">
    {% load static %}
    body {
        background: white url({% static "surveys/images/background.jpg" %}) no-repeat right bottom;
    }


</style><br><br><br>
<div style = "height: 85%; border-radius: 1%; padding: 1px 10px 40px 10px; margin: 0px 400px 0px 400px; background-color:white; box-shadow: inset 0 0 1em black, 0 0 1em black">
<head>
<style>

    .button {

    display: inline-block;
    width: 40%;
    height: 27%;
    cursor: pointer;
    text-align: center;
    outline: none;
    color: #fff;
    font-size: 250%;
    text-decoration: none;
    background-color:dodgerblue;
    border-radius: 5%;
    horizontal-align:middle;
    vertical-align:middle;
    border-color: gray;
    margin: 15px 30px 15px 30px;
    border-style: none;
    box-shadow: inset 0 0 0 black, 0 0 0.3em black
}

.button:hover {background-color: #3e8e41}

.button:active {
  background-color: #3e8e41;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
</style>

<text style = "
font-family: Arial;
font-size: 200%;
width: 70%;
text-align: center;
">




<h1 xmlns="http://www.w3.org/1999/html">{{ question.question_text }} </h1>

</head>
</text>
<div style = "20px 0px 10px 0px; background-color:darkgrey;">
<div style="text-align: center;">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'surveys:vote' question.id %}" method="post">

{% csrf_token %}

{% for option in question.option_set.all %}
    <button class="button" name="option" id="{{ forloop.counter }}" type="submit" value="{{ option.id }}">{{ option.option_text }}</button>
{% endfor %}

</form>

</div>
</div>

surveys/templates/surveys/index.html
<h1>Active Surveys</h1>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'surveys:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No surveys are available.</p>
{% endif %}